// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJdFknk-LVxuCrWhQSeAL2IL9K6oRjxls',
    appId: '1:5706359894:web:8da371d721f48613a347f7',
    messagingSenderId: '5706359894',
    projectId: 'talaskutuphaneleri',
    authDomain: 'talaskutuphaneleri.firebaseapp.com',
    storageBucket: 'talaskutuphaneleri.appspot.com',
    measurementId: 'G-6GEE26NWK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq8K_RmbpSlhaefNVUxSuJmBb8A8bU6-w',
    appId: '1:5706359894:android:af4c7bcb916cf7a4a347f7',
    messagingSenderId: '5706359894',
    projectId: 'talaskutuphaneleri',
    storageBucket: 'talaskutuphaneleri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm-8f7gl3X6nH-aX7dOR5h-3Nkv23Ov-I',
    appId: '1:5706359894:ios:dc943a16f661475ba347f7',
    messagingSenderId: '5706359894',
    projectId: 'talaskutuphaneleri',
    storageBucket: 'talaskutuphaneleri.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm-8f7gl3X6nH-aX7dOR5h-3Nkv23Ov-I',
    appId: '1:5706359894:ios:d1cf5c8172c15e20a347f7',
    messagingSenderId: '5706359894',
    projectId: 'talaskutuphaneleri',
    storageBucket: 'talaskutuphaneleri.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
